apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: elyza-llama  # elyza-llama namespace を指定

patches:
- path: patch.yaml  # patchesStrategicMerge から patches に変更
