---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elyza-llama-3-elyza-jp-8b-gguf
spec:
  template:
    spec:
      containers:
      - name: elyza-llama-3-elyza-jp-8b-gguf
        image: huggingface.co/elyza/Llama-3-ELYZA-JP-8B-GGUF/blob/main/Llama-3-ELYZA-JP-8B-q4_k_m.gguf  # 完全なイメージ名を指定
        #... その他の設定...
